version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
     - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: test
      POSTGRES_PASSWORD: admin
