CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INTEGER(10) NOT NULL,
        EMPLOYEE_NAME VARCHAR(100),
        SALARY DECIMAL(10,2)
    ,CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);
COMMENT ON TABLE EMPLOYEE IS '社員マスタ';

COMMENT ON COLUMN EMPLOYEE.EMPLOYEE_ID IS '社員ID';
COMMENT ON COLUMN EMPLOYEE.EMPLOYEE_NAME IS '氏名';
COMMENT ON COLUMN EMPLOYEE.SALARY IS '給与';
