CREATE TABLE TEST1 (
    KEY  NOT NULL,
        COLUMN1  NOT NULL,
        COLUMN2  NOT NULL,
        COLUMN3  NOT NULL
);
COMMENT ON TABLE TEST1 IS '';

COMMENT ON COLUMN TEST1.KEY IS '';
COMMENT ON COLUMN TEST1.COLUMN1 IS '';
COMMENT ON COLUMN TEST1.COLUMN2 IS '';
COMMENT ON COLUMN TEST1.COLUMN3 IS '';
