CREATE TABLE TEST3 (
    PRIMARYKEY  NOT NULL,
        PRIMARYKEY2  NOT NULL,
        COLUMNA  NOT NULL,
        COLUMNB  NOT NULL
);
COMMENT ON TABLE TEST3 IS '';

COMMENT ON COLUMN TEST3.PRIMARYKEY IS '';
COMMENT ON COLUMN TEST3.PRIMARYKEY2 IS '';
COMMENT ON COLUMN TEST3.COLUMNA IS '';
COMMENT ON COLUMN TEST3.COLUMNB IS '';
