CREATE TABLE TEST2 (
    PRIMARYKEY  NOT NULL,
        COLUMNA  NOT NULL,
        COLUMNB  NOT NULL
);
COMMENT ON TABLE TEST2 IS '';

COMMENT ON COLUMN TEST2.PRIMARYKEY IS '';
COMMENT ON COLUMN TEST2.COLUMNA IS '';
COMMENT ON COLUMN TEST2.COLUMNB IS '';
