openapi: 3.1.0
info:
  title: DbUnitCLI Sidecar API
  description: |
    TauriフロントエンドからcoreプロジェクトのCLI機能を利用するためのREST API仕様です。
    GUIアプリケーションからのリクエストを受け付け、coreプロジェクトの機能を呼び出し、結果をGUI表示用に最適化して返します。
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Micronautアプリケーションサーバー

tags:
  - name: Workspace
    description: |
      ワークスペース全体に関する操作を提供します。
      - ディレクトリ構造の管理
      - 設定ファイルの一覧取得
      - リソースファイルの管理

  - name: Command Settings
    description: |
      各コマンドの設定ファイルに関する操作を提供します。
      対象コマンド:
      - compare: データセット比較
      - convert: フォーマット変換
      - generate: データ生成
      - parameterize: パラメータ化
      - run: コマンド実行

  - name: Resource Files
    description: |
      各種リソースファイルに関する操作を提供します。
      - データセット設定: データセットのメタ情報
      - Excelスキーマ: Excel形式のデータ構造定義
      - テンプレート: データ生成用のテンプレート

  - name: Query Datasource
    description: |
      データソース設定に関する操作を提供します。
      - データベース接続情報の管理
      - クエリー実行用の設定

paths:
  # ワークスペース管理
  /workspace/resources:
    $ref: './paths/workspace.yaml#/paths/~1workspace~1resources'
  /workspace/update:
    $ref: './paths/workspace.yaml#/paths/~1workspace~1update'

  # コマンド設定（基本操作）
  /{command}/add:
    $ref: './paths/command-basic.yaml#/paths/~1{command}~1add'
  /{command}/copy:
    $ref: './paths/command-basic.yaml#/paths/~1{command}~1copy'
  /{command}/delete:
    $ref: './paths/command-basic.yaml#/paths/~1{command}~1delete'
  /{command}/rename:
    $ref: './paths/command-basic.yaml#/paths/~1{command}~1rename'

  # コマンド設定（実行操作）
  /{command}/load:
    $ref: './paths/command-exec.yaml#/paths/~1{command}~1load'
  /{command}/reset:
    $ref: './paths/command-exec.yaml#/paths/~1{command}~1reset'
  /{command}/refresh:
    $ref: './paths/command-exec.yaml#/paths/~1{command}~1refresh'
  /{command}/save:
    $ref: './paths/command-exec.yaml#/paths/~1{command}~1save'
  /{command}/exec:
    $ref: './paths/command-exec.yaml#/paths/~1{command}~1exec'

  # リソースファイル管理
  /{resource}/list:
    $ref: './paths/resource.yaml#/paths/~1{resource}~1list'
  /{resource}/load:
    $ref: './paths/resource.yaml#/paths/~1{resource}~1load'
  /{resource}/save:
    $ref: './paths/resource.yaml#/paths/~1{resource}~1save'
  /{resource}/delete:
    $ref: './paths/resource.yaml#/paths/~1{resource}~1delete'

components:
  schemas:
    # 共通エラーレスポンス
    Error:
      type: object
      properties:
        message:
          type: string
          description: エラーメッセージ
      required:
        - message

  responses:
    ApplicationError:
      description: アプリケーションエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    InternalServerError:
      description: 内部サーバーエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
