package yo.dbunitcli.sidecar;

import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.encoder.PatternLayoutEncoder;
import ch.qos.logback.classic.spi.Configurator;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.classic.tyler.TylerConfiguratorBase;
import ch.qos.logback.core.ConsoleAppender;
import ch.qos.logback.core.rolling.RollingFileAppender;
import ch.qos.logback.core.rolling.TimeBasedRollingPolicy;

/**
 *
 * <p>This file was generated by logback-tyler version 1.0.4</p>
 *
 * <p>Eventual errors and warnings are appended at the end.</p>
 *
 * <p>You may experiment with logback.xml to Java translation, i.e.
 * TylerConfigurator generation, at the following URL:</p>
 *
 * <p>     <a href="https://logback.qos.ch/translator/services/xml2Java.html">...</a> </p>
 *
 * <p>This generated TylerConfigurator class is intended to be copied and integrated
 * into the user's project as a custom configurator. It will configure logback
 * without XML. You are free to rename TylerConfigurator as you wish.</p>
 *
 * <p>It requires logback-classic version 1.5.20 or later at runtime.</p>
 *
 * <p>Custom configurators are looked up via Java's service-provide facility. If a
 * custom provider is found, it takes precedence over logback's own configurators,
 * e.g. DefaultJordanConfigurator.</p>
 *
 * <p>To install your custom configurator to your project, add a
 * provider-configuration file to the following path:</p>
 *
 * <pre>  META-INF/services/ch.qos.logback.classic.spi.Configurator</pre>
 *
 * <p>This provider-configuration file should contain a line with the fully
 * qualified class name of your tyler configurator.</p>
 *
 * <p>See also item 1 of 'Configuration at initialization' section at </p>
 *
 * <p>  <a href="https://logback.qos.ch/manual/configuration.html#auto_configuration">...</a></p>
 *
 * <p>Configurations using TylerConfigurator can still dynamically configure
 * logger levels with the help of properties files. Moreover, configuration
 * files in properties format can be watched for changes. See the
 * documentation on PropertiesConfigurator for more details.</p>
 *
 * <p>https://logback.qos.ch/manual/configuration.html#propertiesConfigurator</p>
 *
 * <p>Please note that when logback-tyler transforms XML to Java, it performs
 * runtime analysis of classes using Java's class reflection. Thus,
 * if your logback.xml mentions classes which are unavailable on the classpath,
 * logback-tyler will fail during the translation.</p>
 *
 */
public class LogbackTylerConfigurator extends TylerConfiguratorBase implements Configurator {
    /**
     * Appender variable referencing the appender named "console".
     */
    protected ConsoleAppender<ILoggingEvent> appenderConsole;
    /**
     * Appender variable referencing the appender named "file".
     */
    protected RollingFileAppender<ILoggingEvent> appenderFile;

    /**
     * <p>This method performs configuration per {@link Configurator} interface.</p>
     *
     * <p>If <code>TylerConfigurator</code> is installed as a configurator service, this
     * method will be called by logback-classic during initialization.</p>
     */
    @Override
    public Configurator.ExecutionStatus configure(LoggerContext loggerContext) {
        this.setContext(loggerContext);
        this.appenderFile = this.setupAppenderFile();
        this.appenderConsole = this.setupAppenderConsole();
        Logger logger_ROOT = this.setupLogger("ROOT", "INFO", null);
        logger_ROOT.addAppender(this.appenderConsole);
        logger_ROOT.addAppender(this.appenderFile);
        return ExecutionStatus.DO_NOT_INVOKE_NEXT_IF_ANY;
    }

    private RollingFileAppender<ILoggingEvent> setupAppenderFile() {
        RollingFileAppender<ILoggingEvent> appender = new RollingFileAppender<>();
        appender.setContext(this.context);
        appender.setName("file");
        appender.setFile("logs/dbunit-cli-sidecar.log");
        appender.setAppend(true);

        // Configure component of type PatternLayoutEncoder
        PatternLayoutEncoder patternLayoutEncoder = new PatternLayoutEncoder();
        patternLayoutEncoder.setContext(this.context);
        patternLayoutEncoder.setPattern("%d{yyyy-MM-dd:HH:mm:ss.SSS} [%t] %-5le %lo [%line] - %msg%n");
        patternLayoutEncoder.setParent(appender);
        patternLayoutEncoder.start();
        // Inject component of type PatternLayoutEncoder into parent
        appender.setEncoder(patternLayoutEncoder);

        // Configure component of type TimeBasedRollingPolicy
        TimeBasedRollingPolicy<ILoggingEvent> timeBasedRollingPolicy = new TimeBasedRollingPolicy<>();
        timeBasedRollingPolicy.setContext(this.context);
        timeBasedRollingPolicy.setFileNamePattern("logs/dbunit-cli-sidecar_%d{yyyy-MM-dd-HH}.log");
        timeBasedRollingPolicy.setMaxHistory(20);
        timeBasedRollingPolicy.setParent(appender);
        timeBasedRollingPolicy.start();
        // Inject component of type TimeBasedRollingPolicy into parent
        appender.setRollingPolicy(timeBasedRollingPolicy);

        appender.start();
        return appender;
    }

    private ConsoleAppender<ILoggingEvent> setupAppenderConsole() {
        ConsoleAppender<ILoggingEvent> appender = new ConsoleAppender<>();
        appender.setContext(this.context);
        appender.setName("console");

        // Configure component of type PatternLayoutEncoder
        PatternLayoutEncoder patternLayoutEncoder = new PatternLayoutEncoder();
        patternLayoutEncoder.setContext(this.context);
        patternLayoutEncoder.setPattern("%d{yyyy-MM-dd:HH:mm:ss.SSS} [%t] %-5le %lo [%line] - %msg%n");
        patternLayoutEncoder.setParent(appender);
        patternLayoutEncoder.start();
        // Inject component of type PatternLayoutEncoder into parent
        appender.setEncoder(patternLayoutEncoder);

        appender.start();
        return appender;
    }
}