# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branche:
      - core/**

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Postgresql startup
        run: docker-compose up -d
      - name: Build with Maven
        run: mvn clean install -fcore/pom.xml -PIntegrationTest
      - name: Create TestReport
        if: always()
        run: mvn allure:report -fcore/pom.xml
      - name: Deploy TestReport
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ./core/target/site/allure-maven-plugin
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: executableJar
          path: ./core/target/**jar-with-dependencies.jar
      - name: Build GUI with Maven
        run: mvn clean package -fgui/pom.xml
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: gui executableJar
          path: ./gui/target/**jar-with-dependencies.jar
