name: tauri-CI
on:
  push:
    paths:
      - 'tauri/**'
      - '.github/workflows/tauri*.yml'
    paths-ignore:
      - '**/.roo/**'
      - '**/docs/**'
  workflow_run:
    workflows: [Java-CI]
    types:
      - completed

jobs:
  build-tauri-push:
    if: ${{ github.event_name == 'push' }}
    runs-on: windows-latest
    steps:
      - name: Run tauri-build
        run: echo "tauri-build executed for push trigger"
      - name: Execute tauri-build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: tauri-build.yml

  build-tauri-workflow:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    steps:
      - name: Run tauri-build
        run: echo "tauri-build executed for workflow_run trigger"
      - name: Execute tauri-build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: tauri-build.yml
