name: tauri-CI
on:
  push:
    paths:
      - 'tauri/**'
      - '.github/workflows/tauri.yml'
  workflow_run:
    workflows: Java-CI
    types:
      - completed

jobs:
  common-steps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get latest successful run-id
        id: get_run_id
        shell: pwsh
        run: |
          $GH_RUN_ID = (curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" `
          "https://api.github.com/repos/y-onodera/dbunitcli/actions/workflows/maven.yml/runs?status=success&per_page=1" `
          | jq -r '.workflow_runs[0].id')
          echo "run-id=$GH_RUN_ID" >> $env:GITHUB_ENV
      - name: Download native-image-sidecar
        uses: actions/download-artifact@v4
        with:
          name: native-image-sidecar
          repository: y-onodera/dbunitcli
          github-token: ${{ secrets.GH_PAT }}
          run-id: ${{ env.run-id }}
      - name: deploy backend
        run: |
          mkdir tauri/src-tauri/backend
          mkdir tauri/src-tauri/backend/lib
          copy -path "*.dll" ./tauri/src-tauri/backend
          copy -path "*.exe" ./tauri/src-tauri/backend
          copy -path "./lib/font*" ./tauri/src-tauri/backend/lib
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: |
          cd tauri
          bun install
          bun tauri build
      - uses: actions/upload-artifact@v4
        with:
          name: installer
          path: ./tauri/src-tauri/target/release/bundle/nsis/*.exe

  build-tauri-push:
    needs: [ common-steps ]
    runs-on: windows-latest
    steps:
      - name: Run common steps
        run: echo "Common steps executed for push trigger"

  build-tauri-workflow:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'Java-CI' && github.event.workflow_run.head_commit.message == 'native-build' }}
    needs: [ common-steps ]
    runs-on: windows-latest
    steps:
      - name: Run common steps
        run: echo "Common steps executed for workflow_run trigger"