name: tauri-CI
on:
  push:
    paths:
      - 'tauri/**'
      - '.github/workflows/tauri.yml'
    workflow-run:
      workflows: Java-CI

jobs:
  build-tauri:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download native-image-sidecar
        uses: actions/download-artifact@v4
        with:
          name: native-image-sidecar
          repository: y-onodera/dbunitcli
          github-token: ${{ secrets.GH_PAT }}
      - name: deploy backend
        run: |
          mkdir tauri/src-tauri/backend
          mkdir tauri/src-tauri/backend/lib
          copy -path "*.dll" ./tauri/src-tauri/backend
          copy -path "*.exe" ./tauri/src-tauri/backend
          copy -path "./lib/font*" ./tauri/src-tauri/backend/lib
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: |
          cd tauri
          bun install
          bun tauri build
      - uses: actions/upload-artifact@v4
        with:
          name: installer
          path: ./tauri/src-tauri/target/release/bundle/nsis/*.exe
